name: workflow
on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
  workflow_dispatch:
jobs:
  sumbodules:
    name: Updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4
        with:
          submodules: recursive
      - name: Setup Git
        run: |
          git config --global user.name 'Git bot'
          git config --global user.email 'bot@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
      - name: Sumbodules
        run: |
          git submodule update --remote --recursive
          git pull && git commit -am "Auto updated submodule references" && git push || echo "Done"
      - name: Setup Node
        uses: actions/setup-node@v2.1.5
      - name: npm
        run: |
          npm install
          npm upgrade
          git pull && git commit -am "Auto updated package.json and package-lock.json" && git push || echo "Done"
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: sumbodules
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4
      - name: Setup Node
        uses: actions/setup-node@v2.1.5
      - name: Install
        run: npm install
      - name: Lint
        run: npm run lint
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: sumbodules
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4
        with:
          submodules: recursive
      - name: Setup Node
        uses: actions/setup-node@v2.1.5
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: .vuepress/dist/
