name: Build/Test/Deploy
on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
jobs:
  sumbodules:
    name: Submodules Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4
        with:
          submodules: recursive
      - name: Sumbodules
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive
          git config --global user.name 'Git bot'
          git config --global user.email 'bot@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull && git commit -am "Auto updated submodule references" && git push && exit 1 || echo "Done"
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: sumbodules
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4
      - name: Setup Node
        uses: actions/setup-node@v2.1.5
      - name: Install
        run: npm install
      - name: Lint
        run: npm run lint
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: sumbodules
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4
        with:
          submodules: recursive
      - name: Setup Node
        uses: actions/setup-node@v2.1.5
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'}}
        with:
          branch: gh-pages
          folder: .vuepress/dist/